# Site settings
title: Dawid Wróbel
email: me@dawidwrobel.com
url: https://wrobelda.github.io
description: "Dawid Wróbel personal landing page."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Dawid Wróbel

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://linkedin.com/in/dawidwrobel
  - title: github
    url: http://github.com/wrobelda    
  - title: facebook
    url: http://facebook.com/wrobel.dawid
  - title: instagram
    url: http://instagram.com/dawidwrobel
  - title: soundcloud
    url: http://soundcloud.com/dwrobel
  - title: spotify
    url: http://open.spotify.com/user/1158128999

# Build settings
markdown: kramdown
permalink: pretty
